server:
  port: 9002
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://lagoucloudeurekaservera:8761/eureka/,http://lagoucloudeurekaserverb:8762/eureka/ #把 eureka 集群中的所有 url 都填写了进来，也可以只写一台，因为各个 eureka server 可以同步注册表
  instance:
    #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: lagou-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: service-user-router
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/user/**
        - id: service-code-router
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/code/**
        - id: service-email-router # 我们自定义的路由 ID，保持唯一
          uri: http://127.0.0.1:8082  # 目标服务地址
          #          uri: lb://lagou-service-email
          predicates:
            - Path=/email/**
management:
  endpoints:
    web:
      exposure:
        include: "*"